#!/bin/sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Add www user.
#======================================================================================================================

bf-adduser www


#======================================================================================================================
# Get Nginx Version.
#======================================================================================================================

cd /tmp

VERSION=$(cat VERSION)
bf-debug "Nginx version ${VERSION}."


#======================================================================================================================
# Install Nginx and dependencies.
#======================================================================================================================

bf-echo "Installing Nginx v${VERSION}..."
apk add --no-cache \
    ca-certificates \
    nginx=${VERSION}
mkdir -p /var/run/nginx
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

CONF_D=/etc/nginx/conf.d
HTTP_D=/etc/nginx/http.d
bf-debug "Cleaning up default Nginx configuration and files."
rm -rf ${CONF_D} ${HTTP_D} /var/www/*


#======================================================================================================================
# Create and link Nginx directories.
#======================================================================================================================

bf-debug "Creating Nginx directories."

mkdir -p /var/lib/nginx
mkdir -p /var/log/nginx-access-logs

mkdir -p ${HTTP_D}
ln -s ${HTTP_D} ${CONF_D} # older builds of Nginx use conf.d instead of http.d

bf-debug "Linking /www to /var/www/localhost."
ln -s /www /var/www/localhost
