#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "NGINX_LIB" "${BF_LIB}/nginx"

BF_NGINX_WWW=/www
bf-env "BF_NGINX_WWW" "${BF_NGINX_WWW}"
bf-env "BF_NGINX_PUBLIC" "${BF_NGINX_PUBLIC_OVERRIDE:-${BF_NGINX_WWW}/public}"
bf-env "BF_NGINX_HELPERS" "/etc/nginx/helpers"
bf-env "BF_NGINX_MODULES" "/etc/nginx/modules"
bf-env "BF_NGINX_LOCALHOST_CONF" "/etc/nginx/sites/localhost.conf"
