#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "NGINX_LIB" "${BF_LIB}/nginx"

bf-env "NGINX_WWW" "/www"
bf-env "NGINX_HELPERS" "/etc/nginx/helpers"
bf-env "NGINX_MODULES" "/etc/nginx/modules"
bf-env "NGINX_LOCALHOST_CONF" "/etc/nginx/sites/localhost.conf"
