#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "NGINX_LIB" "${BF_LIB}/nginx"

NGINX_WWW=/www
bf-env "NGINX_WWW" "${NGINX_WWW}"
bf-env "NGINX_PUBLIC" "${NGINX_PUBLIC_OVERRIDE:-${NGINX_WWW}/public}"
bf-env "NGINX_HELPERS" "/etc/nginx/helpers"
bf-env "NGINX_MODULES" "/etc/nginx/modules"
bf-env "NGINX_LOCALHOST_CONF" "/etc/nginx/sites/localhost.conf"
