#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# From https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/services.d/nginx-access-log/run.
#======================================================================================================================

bf-echo "Starting Nginx access log."
logutil-service -f /var/run/s6/nginx-access-log-fifo /var/log/nginx-access-logs
