#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# From https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/services.d/nginx-access-log/run.
#======================================================================================================================

bcg-echo "Starting Nginx access log"
logutil-service -f /var/run/s6/nginx-access-log-fifo /var/log/nginx-access-logs
