#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Forward Nginx access log to Docker.
#======================================================================================================================

if [ "${BF_NGINX_FORWARD_ACCESS_LOG-}" = "1" ] ; then
    bf-forward ${PWD##*/} /var/log/nginx/access.log
else
    bf-svc-down ${PWD##*/}
fi
