#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Forward Nginx access log to Docker.
#======================================================================================================================

bf-forward nginx-access-log /var/log/nginx/access.log
