#!/bin/bash

chmod +x /usr/bin/healthcheck

chown -R www:www /etc/nginx /var/lib/nginx /www
chmod -R u+rw,go= /etc/nginx /var/lib/nginx /www

chown 65534:65533 /var/log/nginx-access-logs /var/log/nginx-error-logs
chmod u+rwx,og+rw /var/log/nginx-access-logs /var/log/nginx-error-logs
