#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bcg-env "NGINX_LIB" "${BCG_LIB}/nginx"

bcg-env "NGINX_WWW" "/www"
bcg-env "NGINX_LOCALHOST_CONF" "/etc/nginx/sites/localhost.conf"
