#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate configuration files.
#======================================================================================================================

bf-echo "Generating Nginx configuration files..."

NGINX_BASE_CONF=nginx-base.conf
bf-debug " .. ${NGINX_BASE_CONF}"
esh -o ${NGINX_HELPERS}/${NGINX_BASE_CONF} \
    ${BF_TEMPLATES}/${NGINX_BASE_CONF}.esh

NGINX_IGNORE_FAVICON_CONF=nginx-ignore-favicon.conf
bf-debug " .. ${NGINX_IGNORE_FAVICON_CONF}"
esh -o ${NGINX_HELPERS}/${NGINX_IGNORE_FAVICON_CONF} \
    ${BF_TEMPLATES}/${NGINX_IGNORE_FAVICON_CONF}.esh

bf-done
