#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Generate configuration files.
#======================================================================================================================

bcg-echo "Generating Nginx configuration files..."

NGINX_BASE=nginx-base.conf
bcg-debug " .. ${NGINX_BASE}"
esh -o ${NGINX_HELPERS}/${NGINX_BASE} \
    ${BCG_TEMPLATES}/${NGINX_BASE}.esh

bcg-done
