#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Generate helper files.
#======================================================================================================================

bcg-echo "Generate Nginx helper files."

NGINX_BASE=nginx-base.conf
bcg-debug " .. ${NGINX_BASE}."
esh -o ${NGINX_HELPERS}/${NGINX_BASE} \
    ${TEMPLATES}/${NGINX_BASE}.esh
