#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Ensure Nginx is closed gracefully and use base executable to terminate all services.
#
# Nginx flags
#   -s  send a signal to the master process (quit: shut down server gracefully)
#======================================================================================================================

bf-debug "Quitting Nginx." "${BF_E}"
nginx -s quit

bf-svc-finish -t
