#!/bin/withenv sh

set -euo pipefail


#======================================================================================================================
# Run preflight checks.
#======================================================================================================================

nu -c "use bf-nginx run ; run preflight"


#======================================================================================================================
# Start Nginx as a foreground service
# From https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/services.d/nginx/run
#
# Flags:
#   -g  set global configuration directive, in this case turn daemon mode off so it runs as a foreground service
#======================================================================================================================

nginx -g "daemon off;" > /dev/null 2>&1 # send to /dev/null because the log forwarder will show any startup errors
