#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Forward nginx error log to Docker
#======================================================================================================================

if [[ -e /var/log/nginx/error.log ]]; then
    _echo "Forwarding Nginx error log to docker"
    exec tail --follow=name --retry /var/log/nginx/error.log
else
    exec sleep 10
fi
