#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Forward Nginx error log to Docker.
#======================================================================================================================

bf-forward nginx-error-log /var/log/nginx/error.log
