#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E="nginx/$(basename ${0})"


#======================================================================================================================
# Forward Nginx error log to Docker.
#======================================================================================================================

bcg-forward nginx-error-log /var/log/nginx/error.log
