#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Ensure Nginx is closed gracefully and use base executable to terminate all services.
#
# Nginx flags
#   -s  send a signal to the master process (quit: shut down server gracefully)
#======================================================================================================================

nginx -s quit
bcg-terminate
