#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Check argument.
#   1   URL to test
#======================================================================================================================

[[ -z "${1-}" ]] && bcg-error "You must provide a URL to load." "nginx/http-status"
URL=${1}


#======================================================================================================================
# Attempt to load a URL using wget and print the final HTTP status code.
#   (wget follows redirects - we end with tail -1 so we return the final code.)
#======================================================================================================================

wget --server-response --spider "${URL}" 2>&1 | grep "HTTP/" | awk '{print $2}' | tail -1
