name: dev

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  workflow_dispatch:

env:
  TEST_TAG: bfren/nginx:test

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        alpine: [ "3.15", "3.16", "3.17", "3.18", "3.19", "3.20" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Read Nginx version - minor
        uses: bfren/read-file@v2
        with:
          file: ./alpine${{ matrix.alpine }}/overlay/tmp/NGINX_MINOR
        id: nginx_minor
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and export
        id: docker_export
        uses: docker/build-push-action@v6
        with:
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Run tests
        id: docker_test
        run: |
          docker run --entrypoint "/usr/bin/env" ${{ env.TEST_TAG }} -i nu -c "use bf test ; test"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-dev
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}-dev
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-dev
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}-dev
      -
        name: Build and push default
        id: docker_build_default
        if: matrix.alpine == '3.20'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/nginx:dev
            bfren/nginx:${{ steps.version.outputs.contents }}-dev
            ghcr.io/bfren/nginx:dev
            ghcr.io/bfren/nginx:${{ steps.version.outputs.contents }}-dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
