name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        alpine: [ "3.15", "3.16", "3.17", "3.18", "3.19", "3.20" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Read Nginx version - minor
        uses: bfren/read-file@v2
        with:
          file: ./alpine${{ matrix.alpine }}/overlay/tmp/NGINX_MINOR
        id: nginx_minor
      -
        name: Read Nginx version - revision
        uses: bfren/read-file@v2
        with:
          file: ./alpine${{ matrix.alpine }}/overlay/tmp/NGINX_REVISION
        id: nginx_revision
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_PUBLISHING=1
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version_major.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version_minor.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}-alpine${{ matrix.alpine }}
            bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}-alpine${{ matrix.alpine }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
      -
        name: Build and push default (all Nginx versions)
        id: docker_build_default_all
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_PUBLISHING=1
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-${{ steps.version_major.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-${{ steps.version_minor.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}
            ghcr.io/bfren/nginx:nginx${{ steps.nginx_revision.outputs.contents }}-${{ steps.version.outputs.contents }}
      -
        name: Build and push default (latest)
        id: docker_build_default_latest
        if: matrix.alpine == '3.20'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_PUBLISHING=1
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/nginx:latest
            bfren/nginx:${{ steps.version_major.outputs.contents }}
            bfren/nginx:${{ steps.version_minor.outputs.contents }}
            bfren/nginx:${{ steps.version.outputs.contents }}
            ghcr.io/bfren/nginx:latest
            ghcr.io/bfren/nginx:${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/nginx:${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/nginx:${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
