name: publish-alpine3_12

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-alpine3_12:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Read Nginx version - build
        uses: bfren/read-file@v1
        with:
          path: ./alpine3.12/NGINX_BUILD
        id: nginx_build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine3.12/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/nginx:alpine3.12
            bfren/nginx:alpine3.12-${{ steps.version.outputs.contents }}
            bfren/nginx:nginx${{ steps.nginx_build.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
