#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Check argument.
#   1   URL to test
#======================================================================================================================

[[ -z "${1-}" ]] && bf-error "You must provide a URL to test." "nginx/http-test"
URL=${1}


#======================================================================================================================
# Get status.
#======================================================================================================================

STATUS=$(${NGINX_LIB}/http-status "${URL}" || true)


#======================================================================================================================
# Match status:
#   200-399 = ok or redirect (i.e. something is working)
#   400-499 = missing content, permissions error (i.e. something's wrong)
#   500-599 = server errors something is very wrong
#======================================================================================================================

# If STATUS is not a number, something went wrong loading the URL
if echo "${STATUS}" | grep -q '^[0-9]+$' ; then
    bf-error "Unable to load ${URL}." "nginx/http-test"
fi

# Output the status and result
bf-debug "Status ${STATUS}:"
if [ "${STATUS}" -ge 200 ] && [ "${STATUS}" -le 399 ] ; then
    bf-debug "  OK." "nginx/http-test"
elif [ "${STATUS}" -ge 400 ] && [ "${STATUS}" -le 499 ] ; then
    bf-error "  content error." "nginx/http-test"
else
    bf-error "  error." "nginx/http-test"
fi
